name: python ci

on:
  push:
    branches: [ master ]
  jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      
      - name: install
        run: pip install xpinyin
      
      - name: prepare git
        run: |
          git config --global user.email zhuty18@mails.tsinghua.edu.cn
          git config --global user.name zhuty18
  stat:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Readme
        run: cp ./README-o.md ./README.md -f
      - name: Run Statistic
        run: |
          python3 prepare.py -t
