name: Custom Deploy

on: 
  push:
    branches:
      - 'never'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip3 install -r requirements.txt

    - name: Run
      run: python3 update.py -c -page -w

    - name: Upload
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal: ${{secrets.ACCESS_TOKEN}}
        external_repository: zhuty18/zhuty18.github.io
        publish_dir: ./public
        user_name: zhuty18_remote
        user_email: 13718054285@163.com
        publish_branch: gh-pages
